/* Static content and progressive enhancement. No third-party dependencies. */
(() => {
  'use strict';
  const en = {
    brandHome:'Aestum home',skip:'Skip to content',navLabel:'Main navigation',navExamples:'Use cases',navResources:'Free tool',navApproach:'How we work',navAbout:'About',navContact:'Let’s talk <span aria-hidden="true">↗</span>',menuLabel:'Open menu',contactShort:'Contact Aestum',
    heroEyebrow:'MANUFACTURING × CONNECTED WORKFLOWS',heroTitle:'Clear information.<br><span class="text-blue">Work moves forward.</span>',heroDescription:'Orders, materials, and updates live in different places. Aestum helps connect the information and the workflow, so your team knows what to do next.',heroPrimary:'Explore the possibilities <span aria-hidden="true">↗</span>',heroSecondary:'Try the free tool <span aria-hidden="true">→</span>',heroNote:'Start with one real problem. Build around the way you work.',heroVisualLabel:'Manufacturing workflow illustration with fictional data',
    previewTitle:'Operations workspace',sampleShort:'Illustration',previewEyebrow:'WHAT NEEDS ATTENTION',previewHeading:'A clearer place to start.',previewMetric1:'Open questions',previewMetric2:'Next owners',previewMetric3:'Shared view',previewTask1:'15 parts short before the job can start',previewTask1Sub:'WO-208 · Confirm the arrival date',previewTask2:'Next month’s workload needs a review',previewTask2Sub:'Assembly · 120 hours over capacity',previewTask3:'A drawing question needs an answer',previewTask3Sub:'R-21 · Missing dimension blocks review',buyer:'Buyer',planning:'Planning',engineering:'Engineering',previewBottom:'Information → Decision → A clear next step',floatingTitle:'Connect information to action.',floatingText:'Less chasing. More clarity.',contextTitle:'Better tools start with understanding the work.',context1:'Manufacturing & AEC',context2:'Workflows & integration',context3:'Practical automation & AI',
    examplesEyebrow:'START WITH A FAMILIAR PROBLEM',examplesTitle:'Does this look like your workday?',examplesIntro:'Understand the problem before choosing the tool.<br>Four ways to make the next step clearer.',tabsLabel:'Workflow use cases',capacityTab:'Capacity',materialsTab:'Materials',handoffTab:'Handoffs',aiTab:'AI briefs',capacityTitle:'Before promising a date,<br>check the team’s capacity.',capacityText:'Compare estimated remaining work with available hours. Spot an overloaded month early enough to discuss sequencing, staffing, or delivery dates.',decisionLabel:'THE NEXT DECISION',capacityOutcome:'What needs to move, and who will review the plan?',discussScenario:'Let’s discuss this workflow <span aria-hidden="true">↗</span>',capacityDemo:'Assembly · Next three months',fictional:'Fictional data',workHours:'Workload / available hours',chartCapacity:'480 h per month',oct:'October',nov:'November',dec:'December',capacityGap:'November is 120 hours over capacity',capacityAction:'Next: the operations lead reviews the schedule and staffing.',capacityLimit:'An integration starts by checking estimates, team capabilities, and how records stay current.',
    materialsTitle:'On the shelf isn’t the same<br>as available for this job.',materialsText:'Subtract quantities reserved for other jobs, then compare what is left with this job’s needs. Keep the shortage, arrival status, and next owner together.',materialsOutcome:'What is missing, and who will confirm when it arrives?',tryMaterialTool:'Try the material check <span aria-hidden="true">↗</span>',materialsDemo:'WO-208 · Material readiness',stock:'On hand',reservedShort:'Reserved for others',available:'Available',item:'Item',required:'Required',status:'Status',short15:'15 short',quantityReady:'Quantity sufficient',arrivalUnconfirmed:'K-12 arrival date is still unconfirmed',materialsAction:'Next: purchasing confirms supply; the project lead reviews the impact.',
    handoffTitle:'The request was sent.<br>Who has the next move?',handoffText:'Give each request a clear status, owner, and due date. When information is missing or work is blocked, the team can see why and what happened.',handoffOutcome:'Who are we waiting for? What is missing? What counts as done?',handoffDemo:'Request tracking · R-21',waitingInfo:'Waiting for information',drawingRequest:'Fixture drawing clarification',nextOwner:'Next owner',designLead:'Design lead',dueBy:'Review by',oct2:'October 2',event1:'Missing dimension recorded',event2:'Design lead notified',handoffLimit:'A working solution fits your existing forms, email, or task management system.',
    aiTitle:'Surface what matters.<br>Keep people in the loop.',aiText:'Turn reviewed exception records into a brief with traceable sources. A responsible person checks the facts, priorities, and next steps before sharing.',aiOutcome:'What needs attention today, and what is the source?',aiDemo:'Operations brief · For review',prewritten:'Prewritten example',brief1:'November demand exceeds available hours',brief1Text:'Review staffing and work sequencing.',source1:'Source: capacity record C-11',brief2:'WO-208 is short; arrival is unconfirmed',brief2Text:'Purchasing to confirm supply for 15 parts.',source2:'Source: material record M-31',brief3:'A missing dimension is blocking review',brief3Text:'The design lead needs to complete R-21.',source3:'Source: request record R-21',aiReview:'Check facts → Confirm priorities → Assign next steps',aiLimit:'This is a prewritten illustration, not a live AI system or connection to company data.',examplesNote:'These are illustrative workflows, not deployed products or client results. Actual scope depends on your data, process, and users.',
    resourceEyebrow:'ONE SMALL TOOL. ONE USEFUL CHECK.',resourceTitle:'For your next job,<br>are the materials ready?',resourceText:'Use the quantities you already have to run a pre-start check. Identify what is available and what is missing, then take the follow-up list back to your workflow.',resourceFeature1:'No account. Calculate in your browser.',resourceFeature2:'Add your materials and export the results.',resourceFeature3:'Includes a CSV template and a short guide.',resourcePrimary:'Open the free tool <span aria-hidden="true">↗</span>',resourceDownload:'Download CSV template <span aria-hidden="true">↓</span>',resourceLimit:'For a one-time check. Enter your own data; it does not sync with inventory or ERP systems.',toolPreviewLabel:'Open the free material readiness tool',free:'FREE TOOL',toolName:'Material readiness check',toolSubtitle:'One job. A clearer view.',toolSample1:'K-12 · Mount',toolSample2:'F-08 · Fastener',toolSample3:'P-04 · Pad',toolFormats:'Browser calculator · CSV export',
    approachEyebrow:'FIND THE RIGHT FIT, TOGETHER',approachTitle:'Start with one workflow.',approachIntro:'Understand first. Then pilot.<br>A clear scope and next step at every stage.',step1Title:'Understand the real work',step1Text:'Start with a recurring problem. Understand the people, the information they have, their existing tools, and where the work gets stuck.',step1Output:'Clarify: the problem and the workflow',step2Title:'Choose a focused pilot',step2Text:'Decide whether to improve an existing tool, configure a ready-made solution, or build an integration. Agree on what to test and where the limits are.',step2Output:'Define: scope and acceptance criteria',step3Title:'Validate, then put it to work',step3Text:'Let the people doing the work try it and give feedback. If it is useful, plan the rollout, documentation, handoff, and ongoing support.',step3Output:'Deliver: a workflow the team can own',
    aboutEyebrow:'GROUNDED IN REAL WORK',aboutTitle:'Understanding how it’s made.<br>And how it connects.',founderRole:'Manufacturing Technology Consultant',portfolioLink:'Explore my personal portfolio <span aria-hidden="true">↗</span>',aboutLead:'My experience spans architectural manufacturing, digital fabrication, and internal operations systems. Aestum builds on one consistent question: how can technology be useful in the work people actually do?',experience1Title:'Manufacturing workflows & internal systems',experience1Text:'Working across engineering, purchasing, and production to connect information, automation, and everyday use.',experience2Text:'Robotic fabrication and R&D, including digital manufacturing, toolpath workflows, and process integration.',experience3Text:'Stone and architectural manufacturing, translating design intent into executable fabrication workflows.',experienceNote:'These are personal employment experiences, not Aestum client relationships or company endorsements.',
    faqEyebrow:'BEFORE WE START',faqTitle:'A few things to know.',faq1q:'Can we start with just Excel and email?',faq1a:'Yes. Start with your existing digital records. First, check whether the information supports the workflow and who will keep it current. A complete ERP or database is not a prerequisite.',faq2q:'Does the free tool connect to our systems?',faq2a:'The material check uses quantities you enter manually and is designed for a one-time review. Automated sync, shared access, and permissions would need a separately scoped integration.',faq3q:'Are all four use cases ready-made products?',faq3a:'They illustrate possible workflows using fictional data. Your records, process, and responsibilities determine what an actual solution needs to do.',faq4q:'What should I prepare for a first conversation?',faq4a:'Bring one recent example, how you handled it, and the step that takes the most effort. You do not need to share confidential files or system access for an initial conversation.',
    contactEyebrow:'MAKE THE NEXT STEP CONCRETE',contactTitle:'One workflow<br>worth a conversation?',contactText:'Tell me how things work today, and where they get stuck.<br>We can start with a 20-minute conversation.',copyEmail:'Copy email address',topicLabel:'What would you like to discuss?',topicGeneral:'Start with our current workflow',messageLabel:'A recent example',messagePlaceholder:'For example: every time we check whether a job can start, we have to ask purchasing again…',contactButton:'Open an email draft <span aria-hidden="true">↗</span>',contactNote:'Opens your email app. This website does not send the message. You can also email the address shown here.',footerLine:'Real work. Connected information. A clear next step.',privacyLink:'Privacy',
    backToSite:'← Back to Aestum',toolEyebrow:'FREE TOOL / MATERIAL READINESS',toolPageTitle:'See the material gaps before work starts.',toolPageIntro:'For one job, enter the quantity required, stock on hand, and quantities reserved for other jobs. Identify the gaps, then follow up on supply and arrival.',readGuide:'How to use it ↓',toolWorkspaceLabel:'Material readiness worksheet',jobLabel:'Job / project name (optional)',neededDateLabel:'Needed by (optional)',loadSample:'Load example',unitsNote:'Use consistent units within each row. Reservations are for other jobs only.',sampleIndicator:'Fictional sample data',tableScrollLabel:'Material table; scroll horizontally on small screens',tableCaption:'Material quantities and shortage check',materialName:'Material / unit',expectedArrival:'Expected arrival (optional)',checkResult:'Check result',remove:'Remove',emptyRows:'No materials yet. Select “Add material” to start.',addMaterial:'＋ Add material',startBlank:'Start blank',exportCsv:'Export CSV ↓',printCheck:'Print',totalItems:'Material items',shortageItems:'With shortages',verifyItems:'Need verification',toolPrivacy:'Your entries are calculated on this page only. They are not uploaded or automatically saved. Refreshing or closing the page clears them, so export before leaving. Expected arrivals do not count as stock on hand.',
    guideEyebrow:'HOW TO USE IT',guideTitle:'One clear check at a time.',guideIntro:'Use this for a pre-start review of one job. It is not live inventory, purchasing management, or a full scheduling system.',guide1:'<b>Match quantities and units.</b> Use the same unit within each row. Required quantity should be the remaining unissued demand; on-hand stock should exclude materials already issued.',guide2:'<b>Subtract reservations for other jobs.</b> Do not subtract this job’s own reservation again. If your source already reports available stock after reservations, enter it under “On hand” and enter 0 under “Reserved for others.”',guide3:'<b>Check the shortage and arrival.</b> Available = on hand − reserved for others. Shortage = required − available, with a minimum of 0. An expected arrival is not a receipt; purchasing still needs to confirm it.',guide4:'<b>Take the result back to your workflow.</b> Export a CSV or print the check, then assign a follow-up owner and review date. This page has no import or automatic sync. Exports are snapshots for your records.',guide5:'<b>Sufficient quantity still needs a real-world check.</b> This tool does not check specifications, quality, location, batches, or subsequent stock changes. It does not authorize a job to start.',toolCtaText:'Useful check, but gathering the data takes too much work? Let’s look at connecting the Excel files, forms, or systems you already use.',toolCta:'Discuss an integration <span aria-hidden="true">↗</span>',
    privacyTitle:'How this site handles your information',privacyDate:'Updated September 25, 2026',privacy1Title:'Material readiness tool',privacy1:'Job names, materials, and quantities are calculated only in your current browser page. The site does not upload or automatically save them. CSV exports are generated locally by your browser. Refreshing or closing the page clears your entries.',privacy2Title:'Language preference and site use',privacy2:'The site uses browser localStorage to remember your chosen language. You can clear it in your browser settings. The site code includes no advertising trackers, analytics tools, or third-party font services. A hosting provider may retain ordinary connection logs to operate its service.',privacy3Title:'Contacting Aestum',privacy3:'The contact area opens your email application; it does not submit a message through the site. If you send an email, it goes through your email provider and the recipient’s email provider. Do not include passwords, confidential records, or customer personal information in an initial inquiry.',privacy4Title:'External links and questions',privacy4:'External destinations, including the personal portfolio, have their own data practices. For questions about information you have sent to Aestum, contact:',
    copied:'Email address copied.',copyFailed:'Please select and copy the email address above.',draftOpened:'If your email app did not open, use the email address shown here.',closeMenu:'Close menu',confirmReplace:'Replace your current entries? Export first if you want to keep them.',editedData:'Your working data',rowName:'Material {n}',short:'{n} short',availableDetail:'Available: {n}',arrivalPending:'Arrival unconfirmed',arrivalExpected:'Expected: {date}; not yet on hand',arrivalLate:'Expected after the needed date',invalidNumber:'Enter non-negative quantities (up to 1 billion, 6 decimal places).',invalidName:'Enter a material name.',invalidReservation:'Reservations exceed stock. Verify the source quantities.',invalidDate:'Use a valid date from 2000 through 2100.',invalidStatus:'Verify data',summaryInvalid:'{n} item(s) need data corrections before this check can be exported.',summaryShort:'{n} item(s) have shortages. Confirm supply, arrival dates, and who will follow up.',summaryReady:'Quantities are sufficient for the entered demand. Confirm specifications, quality, and actual stock before starting.',summaryEmpty:'Add a material to start the check.',exportDone:'CSV download requested. Keep it as a snapshot; it cannot be imported into this tool.',maxRows:'This one-job check supports up to 100 materials.',exportJob:'Job',exportNeeded:'Needed by',exportItem:'Material / unit',exportRequired:'Required',exportStock:'On hand',exportReserved:'Reserved for other jobs',exportAvailable:'Available',exportShortage:'Shortage',exportArrival:'Expected arrival (not received)',exportStatus:'Status',exportNotes:'Follow-up notes',exportSnapshot:'Snapshot time'
  };
  const zhDynamic = {copied:'已複製 Email。',copyFailed:'請選取上方 Email 地址並複製。',draftOpened:'若郵件程式未開啟，請直接使用上方 Email 地址。',closeMenu:'關閉選單',confirmReplace:'要取代目前的輸入嗎？若要保留，請先匯出。',editedData:'你正在編輯的資料',rowName:'材料 {n}',short:'缺 {n}',availableDetail:'可用量：{n}',arrivalPending:'到貨尚未確認',arrivalExpected:'預計 {date} 到貨，尚未計入庫存',arrivalLate:'預計到貨晚於需要日期',invalidNumber:'請填非負數量（上限十億，小數最多 6 位）。',invalidName:'請填材料名稱。',invalidReservation:'保留量超過現有量，請核對來源數量。',invalidDate:'請填 2000 至 2100 年的有效日期。',invalidStatus:'資料待核對',summaryInvalid:'有 {n} 個項目的資料待核對，修正後才能匯出檢查結果。',summaryShort:'有 {n} 個項目存在數量缺口。請確認供應、到貨日期與後續負責人。',summaryReady:'依輸入數量，目前需求足夠。開工前仍需確認規格、品質與實際庫存。',summaryEmpty:'新增材料，開始這次檢查。',exportDone:'已啟動 CSV 下載。此檔供留存檢查快照，不能重新匯入本工具。',maxRows:'單次工單檢查最多支援 100 項材料。',exportJob:'工單',exportNeeded:'需要日期',exportItem:'材料 / 單位',exportRequired:'需求量',exportStock:'現有量',exportReserved:'其他工單保留量',exportAvailable:'可用量',exportShortage:'缺口',exportArrival:'預計到貨（尚未收到）',exportStatus:'狀態',exportNotes:'後續追蹤',exportSnapshot:'檢查快照時間'};
  const original = new Map();
  document.querySelectorAll('[data-i18n],[data-i18n-aria],[data-i18n-placeholder]').forEach(el => original.set(el, {html:el.innerHTML,aria:el.getAttribute('aria-label'),placeholder:el.getAttribute('placeholder')}));
  for (const [el] of original) { if(el.dataset.i18n && !Object.hasOwn(zhDynamic,el.dataset.i18n)) zhDynamic[el.dataset.i18n]=el.textContent.trim(); }
  zhDynamic.quantityReady='數量足夠';
  const originalTitle = document.title;
  let language = 'zh';
  try { if (localStorage.getItem('aestum-language') === 'en') language = 'en'; } catch { /* storage is optional */ }
  const params = new URLSearchParams(location.search);
  if (['zh','en'].includes(params.get('lang'))) language = params.get('lang');
  const t = (key,values={}) => {
    let value = (language==='en'?en[key]:zhDynamic[key]) ?? en[key] ?? key;
    for (const [name,replacement] of Object.entries(values)) value=value.replaceAll(`{${name}}`,String(replacement));
    return value;
  };
  function applyLanguage(next,save=false) {
    language=next;
    document.documentElement.lang=next==='en'?'en':'zh-Hant';
    for (const [el,initial] of original) {
      if (el.dataset.i18n) el.innerHTML=next==='en'?(en[el.dataset.i18n]??initial.html):initial.html;
      if (el.dataset.i18nAria) el.setAttribute('aria-label',next==='en'?(en[el.dataset.i18nAria]??initial.aria):initial.aria);
      if (el.dataset.i18nPlaceholder) el.setAttribute('placeholder',next==='en'?(en[el.dataset.i18nPlaceholder]??initial.placeholder):initial.placeholder);
    }
    const page=location.pathname.split('/').pop();
    document.title=next==='en'?(page==='material-check.html'?'Free material readiness check — Aestum':page==='privacy.html'?'Privacy — Aestum':'Aestum — Clear information. Work moves forward.'):originalTitle;
    document.querySelectorAll('.lang-toggle').forEach(button=>{button.textContent=next==='en'?'繁中':'EN';button.setAttribute('aria-label',next==='en'?'切換至繁體中文':'Switch to English');});
    document.querySelectorAll('a[href]').forEach(a=>{
      const raw=a.getAttribute('href');
      if (!/^(index|material-check|privacy)\.html(?:[?#]|$)/.test(raw)) return;
      const url=new URL(raw,location.href);url.searchParams.set('lang',next);
      a.setAttribute('href',url.pathname.split('/').pop()+url.search+url.hash);
    });
    if (save) { try { localStorage.setItem('aestum-language',next); } catch { /* optional */ } }
    document.dispatchEvent(new CustomEvent('aestum:language',{detail:{language:next}}));
  }
  const buildInquiry=(topic,message)=>{
    const topicKey={general:'topicGeneral',capacity:'capacityTab',materials:'materialsTab',handoff:'handoffTab',ai:'aiTab'}[topic]||'topicGeneral';
    const zhTopics={topicGeneral:'目前的流程',capacityTab:'產能與交期',materialsTab:'材料與開工',handoffTab:'交接與追蹤',aiTab:'AI 營運摘要'};
    const topicName=language==='en'?en[topicKey]:zhTopics[topicKey];
    const body=language==='en'?`Hi Ester,\n\nI would like to discuss: ${topicName}.\n\n${message.trim()}\n\nName / company:\nGood times to talk:\n`:`Ester 您好，\n\n我想聊聊：${topicName}。\n\n${message.trim()}\n\n姓名／公司：\n方便交流的時段：\n`;
    return `mailto:ester.l@aestum.co?subject=${encodeURIComponent(`Aestum | ${topicName}`)}&body=${encodeURIComponent(body)}`;
  };
  window.Aestum={t,get language(){return language;},applyLanguage,buildInquiry,englishKeys:Object.keys(en)};
  applyLanguage(language);
  document.querySelectorAll('.lang-toggle').forEach(button=>button.addEventListener('click',()=>applyLanguage(language==='en'?'zh':'en',true)));
  const menuButton=document.querySelector('.menu-toggle'), menu=document.getElementById('mobile-nav');
  function closeMenu(returnFocus=false){if(!menu)return;menu.hidden=true;menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label',language==='en'?en.menuLabel:'開啟選單');if(returnFocus)menuButton.focus();}
  menuButton?.addEventListener('click',()=>{menu.hidden=!menu.hidden;menuButton.setAttribute('aria-expanded',String(!menu.hidden));menuButton.setAttribute('aria-label',menu.hidden?(language==='en'?en.menuLabel:'開啟選單'):t('closeMenu'));});
  menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>closeMenu()));
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&menu&&!menu.hidden)closeMenu(true);});
  window.matchMedia('(min-width:821px)').addEventListener('change',event=>{if(event.matches)closeMenu();});
  const tabs=Array.from(document.querySelectorAll('[data-tab]'));
  const activateTab=(tab,focus=false)=>{tabs.forEach(button=>{const active=button===tab;button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;document.getElementById(button.getAttribute('aria-controls')).hidden=!active;});if(focus)tab.focus();};
  tabs.forEach((tab,index)=>{tab.addEventListener('click',()=>activateTab(tab));tab.addEventListener('keydown',event=>{let target;if(event.key==='ArrowRight')target=(index+1)%tabs.length;if(event.key==='ArrowLeft')target=(index+tabs.length-1)%tabs.length;if(event.key==='Home')target=0;if(event.key==='End')target=tabs.length-1;if(target!==undefined){event.preventDefault();activateTab(tabs[target],true);}});});
  const contactTopic=document.getElementById('contact-topic');
  document.querySelectorAll('[data-topic]').forEach(link=>link.addEventListener('click',()=>{if(contactTopic)contactTopic.value=link.dataset.topic;}));
  if(contactTopic&&['general','materials','capacity','handoff','ai'].includes(params.get('topic')))contactTopic.value=params.get('topic');
  document.getElementById('contact-form')?.addEventListener('submit',event=>{event.preventDefault();const uri=buildInquiry(contactTopic.value,document.getElementById('contact-message').value);document.getElementById('contact-status').textContent=t('draftOpened');location.href=uri;});
  document.getElementById('copy-email')?.addEventListener('click',async()=>{
    let copied=false;
    try{await navigator.clipboard.writeText('ester.l@aestum.co');copied=true;}catch{
      const field=document.createElement('textarea');field.value='ester.l@aestum.co';field.style.cssText='position:fixed;opacity:0;left:-9999px';document.body.append(field);field.select();try{copied=document.execCommand('copy');}catch{/* manual fallback */}field.remove();document.getElementById('copy-email').focus();
    }
    document.getElementById('copy-status').textContent=t(copied?'copied':'copyFailed');
  });
})();
